java.compatibility=11
kotlin.compatibility=2.0.21

kdoc.olderVersions=
kdoc.allProjects=true

pom.groupId=com.gradleup.tapmoc
pom.version=0.4.2-SNAPSHOT
pom.description=tapmoc
pom.vcsUrl=https://github.com/GradleUp/tapmoc
pom.developer=tapmoc authors
pom.license=MIT

gcs.bucket=gradleup
gcs.prefix=m2

# kotlin-tasks pulls kotlin-stdlib 2.3
checkDependenciesCompatibility=false
